### ISSUE TITLE
Allow support for process aliases in `config.toml` file

### ISSUE THREAD

**Issue by dileep-kishore** [segrelab/MiCoNE#201]
Allow the user to use aliases for processes instead of having to type out lengthy process names:
```toml
aliases = """
network_inference.direct.flashweave as FW
network_inference.network.make_network as MN
"""
order = """
FW
MN
"""
```

*OR*

```toml
[network_inference.direct.flashweave]
alias = "FW"

[network_inference.network.make_network]
alias = "MN"
```
